name: Run Python Script

on:
  workflow_dispatch:

env: 
  google_api_key: ${{ secrets.GOOGLE_API_KEY }}

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Run Python Script
        run: python app.py
